### ISSUE TITLE
how to pass JWT Token

### ISSUE THREAD

**Issue by felix-0-9** [s0md3v/Arjun#162] opened 2022-05-30 05:15 UTC
I am using the JWT token for authorisation in the header. How to pass it in Arjun. I tried the "--header" option, but it did not work.

Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmZWxpeF8wOV9AZ21haWwuY29tIiwiaWF0IjoxNjUzODg0ODgxLCJleHAiOjE2NTM5NzEyODF9.Ep0Abs-riT5DgEZns9QNdgVjAWFC8ZRlbkq1AYPSf_l-0Y7ab7T4yYjRzv2bBwyc92Ekg1Nsq3i8M7M1HGseMA

**Comment by s0md3v** [comment] 2022-05-30 08:09
Can you share the exact command so I can know that you are supplying it correctly?

**Comment by s0md3v** [comment] 2022-08-27 07:21
Looks like there's some mess up in how your shell interprets command line arguments. You can try using double quotes instead of single quotes.

I am unable to reproduce this and there are no other reports for this so I will close it.

**Closed by s0md3v** 2022-08-27 07:21 UTC
